#  Welcome to NumPy Tutorial

In [1]:
import numpy as np

###  Creating a 1D NumPy array with specific dtype (int8)

In [2]:
arr = np.array([[3, 6, 32, 7]], np.int8)

###  Checking the data type of the array

In [3]:
arr.dtype

dtype('int8')

##    Array Creation

###  Creating a 2D NumPy array using a Python list

In [4]:
lst = np.array([[1, 2, 3], [4, 5, 6]])

### Displaying the array

In [5]:
lst

array([[1, 2, 3],
       [4, 5, 6]])

###  Getting the shape of the array

In [6]:
lst.shape

(2, 3)

###  Creating a 2D NumPy array filled with zeros

In [7]:
z = np.zeros((2, 110))

###  Getting the shape of the zero-filled array

In [8]:
z.shape

(2, 110)

###  Creating a 1D NumPy array using arange

In [9]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###  Creating a 1D NumPy array with evenly spaced values

In [10]:
lnspace = np.linspace(1, 5, 50)
lnspace

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

###  Creating an empty NumPy array with a specific shape

In [11]:
emp = np.empty((2, 5))
emp

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

###  Creating an empty NumPy array with the same shape as an existing array

In [12]:
emplike = np.empty_like(lst)
emplike

array([[1648997520,      32767, 1648997328],
       [     32767,          0,          0]])

###  Creating an identity matrix

In [13]:
inden = np.identity(10)
inden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

###  Getting the shape of the identity matrix

In [14]:
inden.shape

(10, 10)

###  Creating a 1D NumPy array using arange

In [15]:
arr1 = np.arange(56)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

###  Reshaping the array into a 2D array and then raveling it back to 1D

In [16]:
arr1.reshape(28, 2)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

##  Array Manipulation

###  Creating a 2D Python list

In [17]:
arr = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

###  Converting the Python list into a NumPy array

In [18]:
arr = np.array(arr)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

###  Calculating the sum of all elements in the array

In [19]:
arr.sum()

29

###  Transposing the array

In [20]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

###  Getting the number of dimensions of the array

In [21]:
arr.ndim

2

###  Getting the number of bytes used by the array

In [22]:
arr.nbytes

36

###  Getting the index of the maximum element in the array

In [23]:
arr.argmax()

6

###  Getting the index of the minimum element in the array

In [24]:
arr.argmin()

8

###  Getting the indices that would sort the array

In [25]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

###  Getting the index of the maximum element along the specified axis (columns)

In [26]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

###  Getting the indices that would sort the array along the specified axis (columns)

In [27]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

###  Getting the indices that would sort the array along the specified axis (rows)

In [28]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

###  Creating another 2D NumPy array

In [29]:
arr2 = np.array(([5, 1, 2], [51, 6, 7], [8, 1, 2]))

###  Adding two arrays element-wise

In [30]:
arr + arr2

array([[ 6,  3,  5],
       [55, 11, 13],
       [15,  2,  2]])

###  Applying the square root to each element in the array

In [31]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

### Calculating the sum of all elements in the array

In [32]:
arr.sum()

29

###  Finding the minimum value in the array

In [33]:
arr.min()

0

###  Finding the maximum value in the array

In [34]:
arr.max()

7

###  Finding the indices where the elements are greater than 5

In [35]:
np.where(arr > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

###  Finding the indices where the elements are greater than 2

In [36]:
np.where(arr > 2)

(array([0, 1, 1, 1, 2], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))

##  Indexing and Slicing

###  Displaying the array

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

### Slicing the first row of the array

In [38]:
arr[0:1]

array([[1, 2, 3]])

### Slicing from the second row to the end

In [39]:
arr[1:]

array([[4, 5, 6],
       [7, 1, 0]])

### Accessing a specific element in the array

In [40]:
arr[1, 2]

6

###  Slicing the 2nd element of the 0th and 1st row

In [41]:
arr[0:2, 2]

array([3, 6])

###  Slicing the last row, 1st and 2nd columns

In [42]:
arr[-1, 0:2]

array([7, 1])

###  Slicing the entire array for columns 1 and 2

In [43]:
arr[:, 1:3]

array([[2, 3],
       [5, 6],
       [1, 0]])

##  Stacking NumPy Arrays

### Stacking arrays vertically

In [44]:
np.vstack((arr, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  1,  0],
       [ 5,  1,  2],
       [51,  6,  7],
       [ 8,  1,  2]])

###  Stacking arrays horizontally

In [45]:
np.hstack((arr, arr2))

array([[ 1,  2,  3,  5,  1,  2],
       [ 4,  5,  6, 51,  6,  7],
       [ 7,  1,  0,  8,  1,  2]])

###  Splitting the array vertically into 3 parts

In [46]:
np.vsplit(arr, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 1, 0]])]

###  Splitting the array horizontally into 3 parts

In [47]:
np.hsplit(arr, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [1]]),
 array([[3],
        [6],
        [0]])]

##  Indexing with Boolean

###  Creating a 2D NumPy array

In [48]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Creating a Boolean array based on condition (> 4)

In [49]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

###  Using the Boolean array to index the original array

In [50]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

###  Modifying the elements in the original array based on the Boolean array

In [51]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

##  Iterating over a NumPy Array

###  Iterating through the flattened array (1D)

In [52]:
for i in a.flatten():
    print(i)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


###  Iterating through the array in C (row-major) order (1D)

In [53]:
for X in np.nditer(a, order='C'):
    print(X)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1


###  Iterating through the array in Fortran (column-major) order (1D)

In [54]:
for X in np.nditer(a, order='F'):
    print(X)

0
4
-1
1
-1
-1
2
-1
-1
3
-1
-1


###  Iterating through the array in Fortran (column-major) order (2D)

In [55]:
for X in np.nditer(a, order='F', flags=['external_loop']):
    print(X)

[ 0  4 -1]
[ 1 -1 -1]
[ 2 -1 -1]
[ 3 -1 -1]


###  Performing an operation on the elements of the array in-place

In [56]:
for X in np.nditer(a, op_flags=['readwrite']):
    X[...] = X * X
a

array([[ 0,  1,  4,  9],
       [16,  1,  1,  1],
       [ 1,  1,  1,  1]])

###  Creating a 1D NumPy array and reshaping it into a column vector (3x1)

In [57]:
b = np.arange(3, 15, 4).reshape(3, 1)
b

array([[ 3],
       [ 7],
       [11]])

###  Iterating over two arrays simultaneously

In [58]:
for x, y in np.nditer([a, b]):
    print(x, y, sep="\tNext Value\t")

0	Next Value	3
1	Next Value	3
4	Next Value	3
9	Next Value	3
16	Next Value	7
1	Next Value	7
1	Next Value	7
1	Next Value	7
1	Next Value	11
1	Next Value	11
1	Next Value	11
1	Next Value	11
